# Generated by Django 2.0.3 on 2018-03-27 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_rename_number_to_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='full_number',
            new_name='number',
        ),
    ]
