# Generated by Django 2.0.3 on 2018-03-27 14:47

import django
from django.db import migrations, models
from django.db.models import Q


def create_check_constraint(condition, name):
    """
    Create CheckConstraint compatible with Django 4.2 and 5.0+.
    Django 5.0+ uses 'condition' parameter, earlier versions use 'check'.
    """
    if django.VERSION >= (5, 0):
        return models.CheckConstraint(condition=condition, name=name)
    else:
        return models.CheckConstraint(check=condition, name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0012_rename_number_to_sequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='full_number',
            new_name='number',
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=create_check_constraint(
                condition=Q(('cron_string', ''), Q(_negated=True, routine='CUSTOM'), _connector='OR'),
                name='custom_cron_string'
            ),
        ),
    ]
