# Generated by Django 3.1.14 on 2022-12-19 21:56

from django.db import migrations, models
import django_countries.fields
import internationalflavor.vat_number.models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0026_auto_20210622_1055'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='attachments',
        #     field=models.JSONField(blank=True, default=None, null=True, verbose_name='attachments'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='bank_city',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='bank city'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='bank_country',
        #     field=django_countries.fields.CountryField(blank=True, max_length=255, verbose_name='bank country'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='bank_name',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='bank name'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='bank_street',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='bank street and number'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='bank_zip',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='bank ZIP'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='constant_symbol',
        #     field=models.CharField(blank=True, choices=[('0001', '0001 - Payments for goods based on legal and executable decision from legal authority'), ('0008', '0008 - Cashless payments for goods'), ('0038', '0038 - Cashless funds for wages'), ('0058', '0058 - Cashless penalty and delinquency charges'), ('0068', '0068 - Transfer of funds for wages and other personal costs'), ('0138', '0138 - Cashless deductions at source'), ('0168', '0168 - Cashless payments in loans'), ('0178', '0178 - Sales from provided services'), ('0298', '0298 - Other cashless transfers'), ('0304', '0304 - Prior payments for services'), ('0308', '0308 - Cashless payments for services'), ('0358', '0358 - Payments dedicated to payout through post offices'), ('0379', '0379 - Other income, income from postal order'), ('0498', '0498 - Payments in loans'), ('0558', '0558 - Cashless other financial payments'), ('0934', '0934 - Benefits - prior payments'), ('0968', '0968 - Other cashless transfers'), ('1144', '1144 - Prior payment - advance'), ('1148', '1148 - Payment - current advance'), ('1744', '1744 - Accounting of tax at income tax of physical body and corporate body'), ('1748', '1748 - Income tax of physical body and corporate body based on declared tax year'), ('3118', '3118 - Insurance and empl. contrib. to insur. co. and the Labor Office'), ('3344', '3344 - Penalty from message - prior'), ('3348', '3348 - Penalty from message'), ('3354', '3354 - Insurance payments by insurance companies'), ('3558', '3558 - Cashless insurance payments by insurance companies'), ('8147', '8147 - Payment (posted together with the instruction)')], max_length=64, verbose_name='constant symbol'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='currency',
        #     field=models.CharField(choices=[('CZK', 'CZK'), ('EUR', 'EUR'), ('HUF', 'HUF'), ('PLN', 'PLN')], max_length=10, verbose_name='currency'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='customer_city',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='customer city'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='customer_email',
        #     field=models.EmailField(blank=True, max_length=254, verbose_name='customer email'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='customer_phone',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='customer phone'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='customer_registration_id',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='customer Reg. No.'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='customer_street',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='customer street and number'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='customer_tax_id',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='customer Tax No.'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='customer_vat_id',
        #     field=internationalflavor.vat_number.models.VATNumberField(blank=True, verbose_name='customer VAT No.'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='customer_zip',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='customer ZIP'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='date_paid',
        #     field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, verbose_name='date paid', when={'PAID'}),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='date_reminder_sent',
        #     field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date reminder sent'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='date_sent',
        #     field=model_utils.fields.MonitorField(blank=True, default=None, monitor='status', null=True, verbose_name='date sent', when={'SENT'}),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='delivery_method',
        #     field=models.CharField(choices=[('PERSONAL_PICKUP', 'personal pickup'), ('MAILING', 'mailing'), ('DIGITAL', 'digital')], default='PERSONAL_PICKUP', max_length=64, verbose_name='delivery method'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='issuer_email',
        #     field=models.EmailField(blank=True, max_length=254, verbose_name='issuer email'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='issuer_name',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='issuer name'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='issuer_phone',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='issuer phone'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='language',
        #     field=models.CharField(choices=[('en', 'English'), ('pl', 'Polish'), ('cs', 'Czech'), ('sk', 'Slovak'), ('hu', 'Hungarian'), ('ro', 'Romanian')], max_length=10, verbose_name='language'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='note',
        #     field=models.CharField(blank=True, default='Thank you for using our services.', max_length=255, verbose_name='note'),
        # ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, db_index=True, max_length=128, verbose_name='number'),
        ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='payment_method',
        #     field=models.CharField(choices=[('BANK_TRANSFER', 'bank transfer'), ('CASH', 'cash'), ('CASH_ON_DELIVERY', 'cash on delivery'), ('PAYMENT_CARD', 'payment card')], max_length=64, verbose_name='payment method'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='reference',
        #     field=models.CharField(blank=True, max_length=140, verbose_name='reference'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='related_document',
        #     field=models.CharField(blank=True, max_length=100, verbose_name='related document'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='related_invoices',
        #     field=models.ManyToManyField(blank=True, related_name='_invoice_related_invoices_+', to='invoicing.Invoice', verbose_name='related invoices'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='sequence',
        #     field=models.IntegerField(blank=True, db_index=True, verbose_name='sequence'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='shipping_city',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='shipping city'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='shipping_country',
        #     field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='shipping country'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='shipping_name',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='shipping name'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='shipping_street',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='shipping street and number'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='shipping_zip',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='shipping ZIP'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='status',
        #     field=models.CharField(choices=[('NEW', 'new'), ('SENT', 'sent'), ('RETURNED', 'returned'), ('CANCELED', 'canceled'), ('PAID', 'paid'), ('CREDITED', 'credited'), ('UNCOLLECTIBLE', 'uncollectible')], default='NEW', max_length=64, verbose_name='status'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='subtitle',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='subtitle'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='supplier_additional_info',
        #     field=models.JSONField(blank=True, default=None, null=True, verbose_name='supplier additional information'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='supplier_city',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='supplier city'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='supplier_registration_id',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='supplier Reg. No.'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='supplier_street',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='supplier street and number'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='supplier_tax_id',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='supplier Tax No.'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='supplier_vat_id',
        #     field=internationalflavor.vat_number.models.VATNumberField(blank=True, verbose_name='supplier VAT No.'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='supplier_zip',
        #     field=models.CharField(blank=True, max_length=255, verbose_name='supplier ZIP'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='total',
        #     field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='total'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='type',
        #     field=models.CharField(choices=[('INVOICE', 'Invoice'), ('ADVANCE', 'Advance invoice'), ('PROFORMA', 'Proforma invoice'), ('CREDIT_NOTE', 'Credit note')], default='INVOICE', max_length=64, verbose_name='type'),
        # ),
        # migrations.AlterField(
        #     model_name='invoice',
        #     name='vat',
        #     field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='VAT'),
        # ),
        # migrations.AlterField(
        #     model_name='item',
        #     name='title',
        #     field=models.TextField(verbose_name='title'),
        # ),
        # migrations.AlterField(
        #     model_name='item',
        #     name='unit',
        #     field=models.CharField(choices=[('EMPTY', ''), ('PIECES', 'pcs.'), ('HOURS', 'hours')], default='PIECES', max_length=64, verbose_name='unit'),
        # ),
        # migrations.AlterField(
        #     model_name='item',
        #     name='weight',
        #     field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19)], default=0, help_text='ordering', null=True, verbose_name='weight'),
        # ),
    ]
