# Generated by Django 4.0.8 on 2023-12-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0029_auto_20230912_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='supplier_is_vat_payer',
            field=models.BooleanField(blank=True, null=True, default=None)
        ),
    ]
