# Generated by Django 4.2.11 on 2025-10-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0031_update_supplier_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='origin',
            field=models.CharField(choices=[('INCOMING', 'incoming invoice'), ('OUTGOING', 'outgoing invoice')], default='OUTGOING', max_length=8, verbose_name='origin'),
        ),
    ]
