# Generated by Django 4.2.3 on 2025-06-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0031_update_supplier_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='related_invoices',
            field=models.ManyToManyField(blank=True, to='invoicing.invoice'),
        ),
    ]
