# Generated by Django 4.2.3 on 2025-11-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0032_invoice_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='constant_symbol',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='delivery_method',
            field=models.CharField(default='PERSONAL_PICKUP', max_length=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='language',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='NEW', max_length=13),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(default='INVOICE', max_length=11),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(default='PIECES', max_length=6),
        ),
    ]
