# Generated by Django 4.2.3 on 2025-11-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0032_invoice_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='origin',
            field=models.CharField(default='OUTGOING', max_length=9),
        ),
    ]
