# Generated by Django 4.2.3 on 2026-01-13 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0033_alter_invoice_constant_symbol_alter_invoice_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('export_id', models.CharField(db_index=True, max_length=100)),
                ('manager_path', models.CharField(blank=True, default='', max_length=255)),
                ('method_path', models.CharField(blank=True, default='', max_length=255)),
                ('result', models.CharField(max_length=7)),
                ('detail', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_where_creator', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='invoicing.invoice')),
            ],
            options={
                'verbose_name': 'invoice export',
                'verbose_name_plural': 'invoice exports',
                'db_table': 'invoicing_invoice_exports',
                'ordering': ('-created',),
                'default_permissions': ('list', 'view', 'add', 'change', 'delete'),
            },
        ),
        migrations.AddIndex(
            model_name='invoiceexport',
            index=models.Index(fields=['export_id', 'result'], name='inv_export_id_result_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceexport',
            index=models.Index(fields=['manager_path', 'created'], name='inv_export_mgr_created_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceexport',
            index=models.Index(fields=['result', 'created'], name='inv_export_result_created_idx'),
        ),
    ]
