# Generated by Django 4.2.3 on 2026-03-19

from django.db import migrations
from django.utils.translation import gettext_lazy as _

from vies.models import VATINField
from vies.validators import VATINValidator


class Migration(migrations.Migration):
    dependencies = [
        ('invoicing', '0035_alter_item_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='supplier_vat_id',
            field=VATINField(
                verbose_name=_(u'supplier VAT No.'),
                blank=True,
                validators=[VATINValidator(verify=True, validate=False)],
            ),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_vat_id',
            field=VATINField(
                verbose_name=_(u'customer VAT No.'),
                blank=True,
                validators=[VATINValidator(verify=True, validate=False)],
            ),
        ),
    ]

