# Generated by Django 5.2.17 on 2026-10-06 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0036_einvoicing_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EInvoiceTransmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64, verbose_name='provider')),
                ('environment', models.CharField(blank=True, max_length=32, verbose_name='environment')),
                ('document_uuid', models.UUIDField(db_index=True, verbose_name='document UUID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='idempotency key')),
                ('sender_id', models.CharField(max_length=64, verbose_name='sender')),
                ('receiver_id', models.CharField(max_length=64, verbose_name='receiver')),
                ('document_type_id', models.CharField(max_length=500, verbose_name='document type')),
                ('process_id', models.CharField(max_length=255, verbose_name='process')),
                ('customization_id', models.CharField(max_length=255, verbose_name='customization')),
                ('profile_id', models.CharField(max_length=255, verbose_name='profile')),
                ('xml', models.TextField(editable=False, verbose_name='XML')),
                ('xml_sha256', models.CharField(editable=False, max_length=64, verbose_name='XML SHA-256')),
                ('validation_report', models.JSONField(blank=True, default=dict, verbose_name='validation report')),
                ('status', models.CharField(choices=[('PREPARED', 'Prepared'), ('SUBMITTING', 'Submitting'), ('SUBMIT_UNKNOWN', 'Submission outcome unknown'), ('CONFLICT', 'Conflict at provider'), ('REFUSED', 'Refused by provider'), ('SUBMITTED', 'Submitted'), ('DELIVERED', 'Delivered'), ('DELIVERED_NON_PEPPOL', 'Delivered outside Peppol'), ('ACCEPTED', 'Accepted by recipient'), ('UNCONFIRMED', 'Delivered, unconfirmed'), ('REJECTED', 'Rejected'), ('UNDELIVERABLE', 'Undeliverable'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PREPARED', max_length=32, verbose_name='status')),
                ('provider_document_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='provider document ID')),
                ('provider_status', models.CharField(blank=True, max_length=64, verbose_name='provider status')),
                ('last_error', models.JSONField(blank=True, null=True, verbose_name='last error')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='submission attempts')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('provider_received_at', models.DateTimeField(blank=True, null=True, verbose_name='received by provider at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='delivered at')),
                ('last_status_check_at', models.DateTimeField(blank=True, null=True, verbose_name='status last checked at')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='einvoice_transmissions', to='invoicing.invoice', verbose_name='invoice')),
            ],
            options={
                'verbose_name': 'e-invoice transmission',
                'verbose_name_plural': 'e-invoice transmissions',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='EInvoiceTransmissionEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('kind', models.CharField(choices=[('submit', 'submission'), ('status', 'status change'), ('error', 'error')], max_length=16, verbose_name='kind')),
                ('status', models.CharField(blank=True, max_length=32, verbose_name='status')),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='HTTP status')),
                ('provider_code', models.CharField(blank=True, max_length=64, verbose_name='provider code')),
                ('correlation_id', models.CharField(blank=True, max_length=255, verbose_name='correlation ID')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('payload', models.JSONField(blank=True, null=True, verbose_name='payload')),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='invoicing_einvoicing.einvoicetransmission', verbose_name='transmission')),
            ],
            options={
                'verbose_name': 'e-invoice transmission event',
                'verbose_name_plural': 'e-invoice transmission events',
                'ordering': ('created', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='einvoicetransmission',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CANCELLED', 'FAILED', 'REFUSED', 'REJECTED', 'UNDELIVERABLE']), _negated=True), fields=('invoice',), name='einvoice_one_live_transmission_per_invoice'),
        ),
    ]
